version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ticketuser
      POSTGRES_PASSWORD: ticketpass
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DSN: postgres://ticketuser:ticketpass@db:5432/ticketdb?sslmode=disable
    ports:
      - "8080:8080"
    # Wait for db to be ready before starting (optional, for reliability)
    command: ["/bin/sh", "-c", "sleep 5 && ./ticket-app"]

volumes:
  pgdata: 