name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ticketuser
          POSTGRES_PASSWORD: ticketpass
          POSTGRES_DB: ticketdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_DSN: postgres://ticketuser:ticketpass@localhost:5432/ticketdb?sslmode=disable
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod download
      - name: Run Go tests
        run: go test ./...
      - name: Build and run app
        run: |
          go build -o ticket-app ./main
          nohup ./ticket-app &
          sleep 5
      - name: Run API smoke test
        run: sh scripts/api_test.sh 